// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilqwuwlzzzbpkutgbnbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlscXd1d2x6enpicGt1dGdibmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTg5NDQsImV4cCI6MjA3NDEzNDk0NH0.hlGmJSLmW9JqMzJzEVhXq_9lPVH6XsL9ot8Gd-rdCb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});